### ISSUE TITLE
I enabled the plugin with nodebb 0.6.1-dev and it crashed the forum

### ISSUE THREAD

**Issue by furier** [nhitchins/nodebb-plugin-slack#4]
NodeBB v0.6.1-dev Copyright (C) 2013-2014 NodeBB Inc.
    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

    Clustering enabled: Spinning up 1 process(es).

    31/12 01:25 [29238] - info: Time: Wed Dec 31 2014 01:25:58 GMT+0000 (UTC)
    31/12 01:25 [29238] - info: Initializing NodeBB v0.6.1-dev
    31/12 01:26 [29238] - info: Enabling 'trust proxy'
    31/12 01:26 [29238] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
    31/12 01:26 [29238] - error: TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    31/12 01:26 [29238] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
    31/12 01:26 [29238] - error: [plugins/emailer-mandrill] API key not set!
    31/12 01:26 [29238] - info: [app] Database connection closed.

    net.js:1236
        throw new Error('Not running');
              ^
    Error: Not running
        at Server.close (net.js:1236:11)
        at shutdown (/home/sander/nodebb/app.js:374:36)
        at process.<anonymous> (/home/sander/nodebb/app.js:211:7)
        at process.emit (events.js:95:17)
        at process._fatalException (node.js:272:26)
    [cluster] Child Process (29238) has exited (code: 7, signal: null)
    [cluster] Spinning up another process...
    31/12 01:26 [29264] - info: Time: Wed Dec 31 2014 01:26:02 GMT+0000 (UTC)
    31/12 01:26 [29264] - info: Initializing NodeBB v0.6.1-dev
    31/12 01:26 [29264] - info: Enabling 'trust proxy'
    31/12 01:26 [29264] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
    31/12 01:26 [29264] - error: TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    31/12 01:26 [29264] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
    31/12 01:26 [29264] - error: [plugins/emailer-mandrill] API key not set!
    31/12 01:26 [29264] - info: [app] Database connection closed.

    net.js:1236
        throw new Error('Not running');
              ^
    Error: Not running
        at Server.close (net.js:1236:11)
        at shutdown (/home/sander/nodebb/app.js:374:36)
        at process.<anonymous> (/home/sander/nodebb/app.js:211:7)
        at process.emit (events.js:95:17)
        at process._fatalException (node.js:272:26)
    [cluster] Child Process (29264) has exited (code: 7, signal: null)
    [cluster] Spinning up another process...
    31/12 01:26 [29285] - info: Time: Wed Dec 31 2014 01:26:06 GMT+0000 (UTC)
    31/12 01:26 [29285] - info: Initializing NodeBB v0.6.1-dev
    31/12 01:26 [29285] - info: Enabling 'trust proxy'
    31/12 01:26 [29285] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
    31/12 01:26 [29285] - error: TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    31/12 01:26 [29285] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
    31/12 01:26 [29285] - error: [plugins/emailer-mandrill] API key not set!
    31/12 01:26 [29285] - info: [app] Database connection closed.

    net.js:1236
        throw new Error('Not running');
              ^
    Error: Not running
        at Server.close (net.js:1236:11)
        at shutdown (/home/sander/nodebb/app.js:374:36)
        at process.<anonymous> (/home/sander/nodebb/app.js:211:7)
        at process.emit (events.js:95:17)
        at process._fatalException (node.js:272:26)
    [cluster] Child Process (29285) has exited (code: 7, signal: null)
    [cluster] Spinning up another process...
    31/12 01:26 [29306] - info: Time: Wed Dec 31 2014 01:26:10 GMT+0000 (UTC)
    31/12 01:26 [29306] - info: Initializing NodeBB v0.6.1-dev
    31/12 01:26 [29306] - info: Enabling 'trust proxy'
    31/12 01:26 [29306] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
    31/12 01:26 [29306] - error: TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    TypeError: Cannot read property 'buildHeader' of undefined
        at Object.Slack.init [as method] (/home/sander/nodebb/node_modules/nodebb-plugin-slack/library.js:40:57)
        at /home/sander/nodebb/src/plugins/hooks.js:126:13
        at /home/sander/nodebb/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/home/sander/nodebb/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/home/sander/nodebb/node_modules/async/lib/async.js:124:9)
        at fireStaticHook (/home/sander/nodebb/src/plugins/hooks.js:116:9)
        at Object.Plugins.fireHook (/home/sander/nodebb/src/plugins/hooks.js:72:5)
        at Plugins.reloadRoutes (/home/sander/nodebb/src/plugins.js:136:11)
        at /home/sander/nodebb/node_modules/async/lib/async.js:656:23
    31/12 01:26 [29306] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
    31/12 01:26 [29306] - error: [plugins/emailer-mandrill] API key not set!
    31/12 01:26 [29306] - info: [app] Database connection closed.

    net.js:1236
        throw new Error('Not running');
              ^
    Error: Not running
        at Server.close (net.js:1236:11)
        at shutdown (/home/sander/nodebb/app.js:374:36)
        at process.<anonymous> (/home/sander/nodebb/app.js:211:7)
        at process.emit (events.js:95:17)
        at process._fatalException (node.js:272:26)
    3 restarts in 10 seconds, most likely an error on startup. Halting.

**Comment by nhitchins** [comment]
updated for NodeBB 0.6.x
